name: Tests
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ windows-2022, macos-latest, ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 16

      - uses: gradle/gradle-build-action@v2
      - name: Setup and execute Gradle 'test' task
        with:
          arguments: test